Fix weekdays function
parley-messaging/web-library pull request #30
Opened 2022-07-01 08:07 UTC by Gerben-T

part of https://github.com/parley-messaging/web-library-v1/issues/246

2022-07-01 13:15 UTC, gydotitulaer requested changes

2022-07-05 07:40 UTC, Gerben-T commented on cypress/integration/working-hours_spec.js
> +function getTimeInFuture(minutes, hours = 0, days = 0, months = 0, years = 0) {
ja dat is dan niet mogelijk, je moet altijd de waardes er voor invullen volgens mij.
```js
getTimeInFuture(0, 2)
```

2022-07-05 07:40 UTC, Gerben-T commented on cypress/integration/working-hours_spec.js
> +function getTimeInFuture(minutes, hours = 0, days = 0, months = 0, years = 0) {
Maar misschien doet iemand liever 

```js
getTimeInFuture(2 * 60)
```

2022-07-05 07:41 UTC, Gerben-T commented on cypress/integration/working-hours_spec.js
> +function getTimeInPast(minutes, hours = 0, days = 0, months = 0, years = 0) {
Zelfde reactie hier; https://github.com/parley-messaging/web-library/pull/30#discussion_r913482854

2022-07-05 07:43 UTC, Gerben-T commented on cypress/integration/working-hours_spec.js
> +function getTimeInFuture(minutes, hours = 0, days = 0, months = 0, years = 0) {
Om dit te kunnen doen moet je https://simonsmith.io/destructuring-objects-as-function-parameters-in-es6 toepassen, maar vind ik te overdreven

2022-07-08 07:31 UTC, gydotitulaer approved these changes

2022-07-08 07:43 UTC, gydotitulaer approved these changes

2022-07-08 07:46 UTC, merged